title = "PROGRAM config file"

[connection]
host = "127.0.0.1"
port = "5432"
user = "postgres"
database = "mecao"
password = ""
autocommit = false

[estepa]
method = "f-spread"
lna = false
autolimits = false
limmin = 590
limmax = 600
chunks = 8

[directory]
res_directory = "D:/Documentos/Resultados"
work_directory = "D:/Escritorio/ESTEPA/Files"
