title = "PROGRAM config file"

[connection]
host = "opter6.cnm.es"
port = "5432"
user = "joaquin"
database = "mecao"
password = ""
autocommit = false

[estepa]
method = "f-spread"
lna = false
autolimits = false
limmin = 590
limmax = 600
chunks = 2

[directory]
res_directory = "D:/USUARIS/AKAIYFS/Documents/ESTEPA/Results"
work_directory = "D:/USUARIS/AKAIYFS/Desktop/ESTEPA ACTUAL/Files/"
