title = "PROGRAM config file"

[connection]
host = "127.0.0.1"
port = "5432"
user = "postgres"
database = "mecao"
password = "Delo31898"
autocommit = false

[estepa]
method = "none"
lna = true
autolimits = true
limmin = 590
limmax = 600
chunks = 2

[directory]
res_directory = "D:/USUARIS/AKAIYFS/Desktop/ESTEPA v8/Results"
work_directory = "D:/USUARIS/AKAIYFS/Desktop/ESTEPA v8/Files"
