title = "PROGRAM config file"

[connection]
user = "guest"
autocommit = false

[estepa]
method = "none"
lna = false
autolimits = false
limmin = 0
limmax = 600
chunks = 12

[directory]
res_directory = "D:/USUARIS/AKAIYFS/Desktop/ESTEPA ACTUAL"